### ISSUE TITLE
Saffron Fighting Dojo Broken

### ISSUE THREAD

**Issue by apokeguy** [Vortyne/pureRGB#12]
When you enter the Fighting Dojo on the left, it registers as Sabrina's gym. If you enter the gym before fighting Team Rocket upon leaving you get trapped at the doorway of Sabrina's gym due to the rocket member standing in the way.

Both gyms register as Sabrina's.

**Comment by Vortyne** [comment]
Ah, I recall this. It was a test change I made to be able to get into saffron gym more easily. Seems I forgot to remove that change. I will make a release.

**Comment by Vortyne** [comment]
Fixed in v2.04 https://github.com/Vortyne/pureRGB/releases/tag/v2.04
