### ISSUE TITLE
Overworld abilities (flash/dig) not working properly

### ISSUE THREAD

**Issue by Darknesshade** [Vortyne/pureRGB#21]
Hello,

I've been enjoying your mod and wanted to make an account on here to let you know about an issue I found.
I am only 3 badges in right now, so I don't know about the rest of the overworld abilities yet, but Flash and Dig are not registering as the proper ability.
When I use 'Dig', it says a blinding flash lights the area (uses flash)
When I use 'Flash', it says that I need a new badge (it is activating either surf/fly/or strength) - despite the fact that I already have the boulder badge.

Thanks for making this mod. I've been itching to play Gen 1 again after seeing sprites and old gen 1 art and then randomly came across a post mentioning your mod on Reddit.

Regards,
DS

**Comment by Vortyne** [comment]
Already fixed in 2.3.1 since two days ago
