### ISSUE TITLE
Hyper beam issue

### ISSUE THREAD

**Issue by MarcussucraM** [Vortyne/pureRGB#22]
After AI uses hyper beam the recharge state persists? Recently went through the elite 4 and any pokemon that used hyper beam would stop attacking entirely afterwards. Allowing for things like triple swords dance set up sweeps with 0 threat.

**Comment by Vortyne** [comment]
I'll take a look

**Comment by Vortyne** [comment]
If you could provide more information: for example, which moves you were using, which opponent you were facing, etc. it may help finding the issue.

**Comment by Vortyne** [comment]
I see the issue, and I will fix it in the next release.
