### ISSUE TITLE
Pokemon Center issues

### ISSUE THREAD

**Issue by NoSleepUntilVacation** [Vortyne/pureRGB#23]
I had saved in the Vermilion City pokemon center before upgrading from PureGreen 2.3.1 to 2.3.2, but when I opened the game, the center's graphics were glitchy and there were invisible walls surrounding me. When I temporarily downgraded to 2.3.1, the center worked as intended. After leaving, I saved outside and upgraded again; so far, the game has worked properly since then, but whenever I heal at any pokemon center, the pokeballs in the machine are just a mass of pixels. They appear normally if I try healing a second time. Since upgrading, I tried saving and exiting in the same pokemon center, and I didn't run into the trapping glitch again.
![puregreen healing glitch](https://user-images.githubusercontent.com/122333957/211458033-71721954-369a-426a-86a4-5026fad76336.png)

**Comment by Vortyne** [comment]
The sprite glitchiness I am aware of, it's something we're trying to figure out. It's due to the wobbliness of sprites fix that was in 2.3.2.

It's normal for this invisible wall stuff to happen when you upgrade. It's because the code has changed, and the save file hasn't. It's usually fixed by loading a new area. You can either fly somewhere else or use Pocket Abra to fix it.

**Comment by epman100** [comment]
I was facing a similar problem to what NoSleepUntilVacation was experiencing but for me it was from PureBlue v2.3.3 to the newly released 2.4.0 version and this was the result in saving the game in Vermilion City Pokemon center from the 2.3.3 version and then loading that game save into the 2.4.0 version.

![Pokemon_PureBlue_v240](https://user-images.githubusercontent.com/61091896/229208802-d43af1cc-47d8-4d9c-87b6-df75ca6420f5.png)

much worse graphical glitches than the OP

**Comment by Vortyne** [comment]
> I was facing a similar problem to what NoSleepUntilVacation was experiencing but for me it was from PureBlue v2.3.3 to the newly released 2.4.0 version and this was the result in saving the game in Vermilion City Pokemon center from the 2.3.3 version and then loading that game save into the 2.4.0 version.
> 
> ![Pokemon_PureBlue_v240](https://user-images.githubusercontent.com/61091896/229208802-d43af1cc-47d8-4d9c-87b6-df75ca6420f5.png)
> 
> much worse graphical glitches than the OP and getting stuck & cannot move at all from 2.3x to 2.4.0. this was reproduced in BGB emulator 1.5.10 fortunately I had a pocket abra already in the bag to clear up that problem (but others may not be so fortunate if pocket abra was not yet obtained in pewter city if they haven't reached that point yet)
> 
> sometimes it would be great if some sort of "softlock warp" from the [shinpokemon games](https://github.com/jojobear13/shinpokered/) were implemented into pureRGB

This issue (as far as I know) only arises from changing versions - which is a problem that will go away when I stop adding large features to the game. So I don't wish to fix it in a better way at the moment.

If there is an issue that requires warping to another map on the current version without changing versions - then I will fix that bug. However I cannot support full save compatibility on this game and still update it frequently with new features.
