### ISSUE TITLE
A couple of minor bugs related to v2.3.3

### ISSUE THREAD

**Issue by ViWalls** [Vortyne/pureRGB#24]
- There is a strange situation when you jump into the hole where you must push the rock to open the last barrier in Victory Road. Red sprite it's static in the ground and then it dissapears when the fall animation starts. I haven't tried in other holes yet, but something happens with that sprite placement because is not supposed to be there until the character sprite falls.

- The final battle against Blue after beating Elite Four has battle animations even if you turn off battle animations.

I will take advantage of this report to say PureRGB is one of the best romhacks that I ever played in my entire life. This overhaul of Gen 1 it's beyond imagination, and it's true you can use more pkmn than usual and battles are more challenging. You made an excellent job around something that always annoyed me: a game about catching all pkmn but with just a few runnable ones transformed into a more complex meta. Said that, the good ones of Gen 1 are still better than the rest but you can have fun and complete the game with almost every team you want. The movesets and learnset re-design are original and have common sense, pretty inspired by beta and loyal to the style of the game.

In my first run I found more efficient play with only two pkmn, Nidoking and Mew (plus another Mew as HM Slave) because level an entire team will result in underlevel matches when with just two I always matched or just surpassed opponents at end game by two or three levels as much. It took me 7h 13m to complete the game (considering I'm used to speedrunning Gen 1 randomized runs, but the changes of pkmn and move/movesets made the progress slower due to re-learning) battling every trainer in Gyms plus the ones on S.S. Anne and Sylph Co. Office Building to maintain my level (and because those battles are accessible one time, with the exception of S.S. Anne that I discovered later it can return) and ended the game with both at level 71 and 70. I had a great experience playing through this romhack from start to end. The different palettes of special pkmn assigned to specific zones it's such an original idea applied in a simple way that works excellent for Gen 1.

As a curious detail, the guy of Mew Glitch (route 25) doesn't gives you Mew but the girl below him it does. Then, the guy blocking the path to the TM after the Hiker next to this girl gives you another Mew using the glitch again. Because Mew has a fixed moveset due to the one you can find in the back of the truck, you can get a lvl 7 Mew with Psychic and Recover so early two times in Route 25. This is not a critic, in fact I kind of like it and idk if it was intended or not but I would love if stay like this in the future!

To conclude and as a suggestion, I would like to see in the future a tab when you are in battle moving through your pkmn moves like speedchoice showing accuracy and power of moves plus the effect. I know the movedex exist but sometimes you must choose between some moves without the knowledge of those attacks or effects and this force players to learn, use in battle, end the battle, compare in movedex and reset plus load your save if is not what you want. It's difficult choose moves in the middle of battle and this forced me to load a bunch of times!

**Comment by Vortyne** [comment]
`The final battle against Blue after beating Elite Four has battle animations even if you turn off battle animations.`

this is a feature from the original game - it's intended behaviour, I didn't change anything with that. The original game turns on animations for the final battle to make it more "epic".

As for the falling through hole animation, this fall animation visual bug I believe is in the original game as well.

**Comment by Vortyne** [comment]
At the moment I am hesitant to add more information about moves into the battle interface, as I think the player should make use of the movedex or pokedex. Maybe I should make them accessible in battle. I know it may result in the player reloading the game - but this is part of learning.

**Comment by Vortyne** [comment]
The falling through hole animation bug may in fact not be in the original game - I'll take a look at seeing if I can fix that for the next release.

**Comment by ViWalls** [comment]
> `The final battle against Blue after beating Elite Four has battle animations even if you turn off battle animations.`
> 
> this is a feature from the original game - it's intended behaviour, I didn't change anything with that. The original game turns on animations for the final battle to make it more "epic".
> 
Yes, you're right. After hundreds of runs with speedchoice I forgot about it. Speedchoice changes this and all battle animations are off, including the last one against Blue.

**Comment by ViWalls** [comment]
> At the moment I am hesitant to add more information about moves into the battle interface, as I think the player should make use of the movedex or pokedex. Maybe I should make them accessible in battle. I know it may result in the player reloading the game - but this is part of learning.

Access to movedex in battle it's such a nice idea. I think that option will solve everything, but you must learn the moves anyways so it keeps that essence of learning curve. Implementing movedex to the game was a solid feature, because you must complete two dex in one game.

**Comment by ViWalls** [comment]
> The falling through hole animation bug may in fact not be in the original game - I'll take a look at seeing if I can fix that for the next release.

I'm playing vanilla now looking for it and indeed this doesn't happens in original release. Thank you for your dedication and again, this romhack it's an excellent job. Keep up the good work!

**Comment by Vortyne** [comment]
I found the cave entry visual bug and will fix in the next version
