### ISSUE TITLE
CinnabarLabColorChanger.asm issue

### ISSUE THREAD

**Issue by Raichusaur** [Vortyne/pureRGB#27]
When you ask for color change and you don't have any more, text is wrongly displayed.

I think the bug is here:

_LabColorChangerNoChangesLeft::
	text "You don't have"
	cont "any color changes"
	cont "left!"
	para "1 change per 10"
	line "#MON caught!"
	prompt

Maybe (cont "any color changes") should be (line "any color changes")?

**Comment by Vortyne** [comment]
You're right - the first `cont` should be `line`

**Comment by Vortyne** [comment]
I'll fix it in the next release
