### ISSUE TITLE
Scrambled graphics pokedex glitch

### ISSUE THREAD

**Issue by Cavencruiser** [Vortyne/pureRGB#28]
This occurs when you open the pokedex, view a pokemon's description, go back, press select for the map inside the pokedex menu, and then press b to exit, all in that order. The graphics of the overworld will now be scrambled until you either open the dex again or enter a building.

**Comment by Vortyne** [comment]
What version are you using?

**Comment by Vortyne** [comment]
Nevermind - it seems to be present in the latest version. I'll have a look

**Comment by Vortyne** [comment]
It's something simple to fix. I'll fix it in the next version.

**Comment by Cavencruiser** [comment]
Glad to hear, thanks for the feedback on the issue
