### ISSUE TITLE
Question about secret area.

### ISSUE THREAD

**Issue by Soraftw23** [Vortyne/pureRGB#33]
What does the topsecretkey do? I have mew and mewtwo in my party in the secret area and can't figure out what it does or how to get the armor on mewtwo. Thanks.

**Comment by Vortyne** [comment]
Talk to giovanni with mewtwo in your party (bills garden) and you get a hint

this is as much information as I can give about it, it's a secret area

**Comment by Soraftw23** [comment]
Thanks for your help, the puzzle is way too difficult though, hope to see a change to it in a future update, other than that the hack was really fun.

**Comment by Vortyne** [comment]
I'm not going to change it
