### ISSUE TITLE
Graphic glitches when switching from OG to OG+ Icons

### ISSUE THREAD

**Issue by Soljanka** [Vortyne/pureRGB#34]
When switching from OG to OG+ Icons the game glitches in the menu and overworld:
![OG+](https://user-images.githubusercontent.com/7444116/232258130-e6c62279-2aed-484e-a4bb-7e24cee7f7ec.PNG)
![OG+2](https://user-images.githubusercontent.com/7444116/232258141-f3992599-22a5-4c17-ae67-e6e408c4d312.PNG)

both 2.4.0 and 2.4.1 have this issue - version 2.3.3 is fine

**Comment by Vortyne** [comment]
At the moment I've only seen this happen in red's house, and doesn't appear to cause permanent issues. May fix it in the next release.

**Comment by Vortyne** [comment]
I believe this happens only in maps with no sprites. I will fix it soon.

**Comment by Vortyne** [comment]
Fixed in v2.4.2
