### ISSUE TITLE
Giovanni's Textbox glitching out

### ISSUE THREAD

**Issue by UltimateKirb** [Vortyne/pureRGB#35]
When talking to Giovanni after defeating him, a textbox displays which then glitches out and the text that displays is the same text as giving the Super Nerd the Old Amber. Another time I tried, the palette glitched out (second picture). 

If it matters, I performed the MissingNo. Cinnabar glitch and encountered MissingNo. a second time in the Cerulean Rocket House with the giant machine. 

![Pokémon PureRed_1682438779670](https://user-images.githubusercontent.com/131792985/234338051-357c08de-74ff-4184-9aeb-bfe7c68e7d2d.png)
![Pokémon PureRed_1682439076936](https://user-images.githubusercontent.com/131792985/234338056-e0448b24-2b53-4d8e-b673-1cada8d337fe.png)

**Comment by Vortyne** [comment]
There was a typo on a line of code.

**Comment by Vortyne** [comment]
I will fix it soon.

**Comment by Vortyne** [comment]
Added a fix, will put it in the next release

**Comment by UltimateKirb** [comment]
> Added a fix, will put it in the next release

Nice! If I may ask, what is the textbox meant to display? I saved after experiencing this bug, so I'm unsure what he is meant to say there.

**Comment by Vortyne** [comment]
same thing as the original game, "Blah blah team rocket is finished i must go" only change is that his theme music was made to play if the feature was turned on
