### ISSUE TITLE
Switch mode it's asking to change mons even if the rest of your team is fainted (v2.4.2)

### ISSUE THREAD

**Issue by ViWalls** [Vortyne/pureRGB#36]
Example: I'm playing with Nidoking and Charmeleon, Charmeleon it's fainted. Every time the enemy trainer uses a new pokémon in battle, the game will ask if I want to change to other mon even if it's not possible. So it's doesn't detect if the rest of your team is fainted when the proper behaviour it's skip the switch message if you have only one healthy mon.

**Comment by Vortyne** [comment]
This is how the original game worked

**Comment by Vortyne** [comment]
Might fix it in next version but not a huge priority at the moment
