### ISSUE TITLE
Bill's PC Boxes Glitched Out

### ISSUE THREAD

**Issue by saberbreaker** [Vortyne/pureRGB#37]
Hi there,

Sorry I don't have any good technical way to explain this, but I'll do my best.

After reaching Fushia City and doing some things here and there, I went back to my PC to change boxes. Despite only having enough to be using 3/4 boxes, all boxes had the Pokeball symbol next to them. When I went in and looked at the boxes, they were all completely empty. I'm not entirely sure what was the trigger here, but it was an issue.

Was playing using Gambatte on an Anbernic RG35XX running Garlic OS.

**Comment by Vortyne** [comment]
So the unused boxes were empty, but the used boxes were normal when you looked at them?

**Comment by Vortyne** [comment]
It sounds like an issue with the emulator reading from SRAM (save file) correctly

**Comment by Vortyne** [comment]
At the moment I am unable to reproduce or find an issue with the wBoxMonCounts data assignments - which are what decides the numbers that display on the screen and whether the pokeballs show up.

**Comment by Vortyne** [comment]
try the latest version of Ganbatte - and if you still have an issue, perhaps this is an issue with that emulator

**Comment by Vortyne** [comment]
closed due to inactivity
