### ISSUE TITLE
Able to surf on impassable block.

### ISSUE THREAD

**Issue by AlphaRage** [Vortyne/pureRGB#38]
I found a specific corner block on the seafoam islands that I can surf on and dismount from. However, it is only possible to move onto it from the water, but not from the land.

![image](https://github.com/Vortyne/pureRGB/assets/16274094/83d78d9a-64cc-4c58-bdb2-14f735380a4f)

**Comment by Vortyne** [comment]
Thought I fixed this issue, will take another look

**Comment by Vortyne** [comment]
I fixed half of it, but missed the water collision check portion. I will update it. Actually I can reuse code and save some space when fixing this.

**Comment by Vortyne** [comment]
Should be fixed in next release
