### ISSUE TITLE
ROM doesn’t like to work for more than a day?

### ISSUE THREAD

**Issue by Mumpmander** [Vortyne/pureRGB#39]
I recently injected your PureBlue v2.4.3 ROM into a Game Boy Color emulator via NSUI for my subreddit. It is to be played on a 3DS. The user who requested it said the game worked fine the first day but now it does not boot up. He says it’s just a black screen. He deleted and redownloaded to no avail. Is there a known bug that would do this or would this be a me problem? Here is my post: [here](https://www.reddit.com/r/3dsqrcodes/comments/1466xno/pok%C3%A9mon_pureblue_v243_gb_hack/?utm_source=share&utm_medium=ios_app&utm_name=ioscss&utm_content=1&utm_term=1) If you need more info or have any ideas, I’d be happy to answer. Thank you! 

-Mumpmander

**Comment by Vortyne** [comment]
Please only report bugs if you are the person playing the game and can describe exactly what happened
Save data doesn't have any effect on the game even booting up - if it doesn't boot up but did before, this is most likely an emulator problem

**Comment by Vortyne** [comment]
Closed due to inactivity
