### ISSUE TITLE
[2.4.4] Seismic Toss displays type effectiveness.

### ISSUE THREAD

**Issue by BritishCynic** [Vortyne/pureRGB#41]
As Seismic Toss should ignore type effectiveness, this move should completely ignore type effectiveness and just deal its intended damage, but the move displays type effectiveness messages.

**Comment by Vortyne** [comment]
Due to changing it to fighting type, it displays type effectiveness in some cases - in the original game due to being normal type it just showed normal type effectiveness

**Comment by BritishCynic** [comment]
... Seismic Toss was always a fighting-type move in Generation I.

**Comment by Vortyne** [comment]
Whoops, that means I made a mistake and created that bug

**Comment by Vortyne** [comment]
Seems the bug may have been created when I modified psywave. This was pretty early on. I must have removed SPECIAL_DAMAGE_EFFECT from the SetDamageEffects array and should have kept it in there due to sonic boom and seismic toss.

**Comment by Vortyne** [comment]
Should be fixed in the next version
