### ISSUE TITLE
Flicker when walking/running on a Gameboy Color

### ISSUE THREAD

**Issue by Desousak** [Vortyne/pureRGB#42]
I've noticed that when walking or running, the graphics in the game seem to visually "jerk" or stutter, which isn't noticeable with different rom hacks of Pokemon red/blue. I can't tell if this happens on an emulator - but I'm getting this behavior on original GBC hardware. I noticed it with a original unmodded gameboy and also with an ips-modded one as well.

Here's some footage of the stutter in pallet town (most noticeable with the roof on Prof. Oaks building):

https://github.com/Vortyne/pureRGB/assets/25018536/34626d12-6fdc-4ca7-9358-b08e809a1737

Here's the same pallet town in another romhack ([shinpokered](https://github.com/jojobear13/shinpokered)):

https://github.com/Vortyne/pureRGB/assets/25018536/bab9b2ad-a312-4b2f-92e8-777fb7efcb9b

**Comment by Vortyne** [comment]
I'll do some comparisons with shinpokered while working on the next release to see if I'm missing any fixes from the overworld code

**Comment by Vortyne** [comment]
jojobear mentioned that he has some new code to get GBC to use double speed CPU mode when in the overworld to make it run as smooth as possible - haven't added in that code yet

**Comment by jojobear13** [comment]
Here are the relevant commits:

> cffd00e5 use 2x cpu mode when playing in 60fps on GBC
> 0638fea4 fixed ss anne leaving when cpu in 2x mode

**Comment by Vortyne** [comment]
probably fixed in the next release, let me know if not
