### ISSUE TITLE
Pocket Abra acting different to dialogue

### ISSUE THREAD

**Issue by BritishCynic** [Vortyne/pureRGB#43]
Pocket Abra (possible the Teleport move itself too), doesn't actually return you to the last Pokémon Center you used if Fly is used, and instead returns you to the destination you last flew to if Fly was used at any point before you next use a Pokémon Center.

**Comment by Vortyne** [comment]
This is intended - both teleport and pocket abra work set the "return to this pokemon center" value when:
1. You enter a pokemon center (versus having used the heal dialogue at like the original game)
2. You use fly

I realize this is different than the original game, but I intentionally changed that.
