### ISSUE TITLE
Movedex doesn't register moves used by enemy Pokémon which my Pokémon are immune to.

### ISSUE THREAD

**Issue by GraionDilach** [Vortyne/pureRGB#45]
Reached the Lass with the Level 14 Jigglypuff. My lead was a Dodou. The Jigglypuff used Sing, and the "It doesn't affect Dodou..." message popped out. I was surprised to I took a note to check it in the Movedex after the battle, but it wasn't even registered there.

Version v2.4.5 on the Gambatte version included in OnionOS 4.2.0 RC on a Miyoo Mini Plus.

**Comment by Vortyne** [comment]
The movedex only registers moves you've seen used successfully

That's how it was designed

Basically, if you've seen the animation, it is in the movedex now

otherwise, it isn't
