### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by Neves97** [Vortyne/pureRGB#47]
```
rgbgfx  -o gfx/pokemon/front/beedrill.2bpp gfx/pokemon/front/beedrill.png
warning: Fusing colors #fcfcfcff and #ffffffff into Game Boy color $7fff [first seen at x: 46, y: 42]
rgbgfx: /home/rgbds-0.6.1/src/gfx/process.cpp:662: static uint16_t TileData::rowBitplanes(const Png::TilesVisitor::Tile&, const Palette&, uint32_t): Assertion `index < palette.size()' failed.
Makefile:194: recipe for target 'gfx/pokemon/front/beedrill.2bpp' failed
make: *** [gfx/pokemon/front/beedrill.2bpp] Aborted
make: *** Deleting file 'gfx/pokemon/front/beedrill.2bpp'
root@DESKTOP-S0K7P95:/home/pureRGB#
```

I am on commit 508a46b, fresh cloned.
Can build PokeRed just fine on Ubuntu.

**Comment by Vortyne** [comment]
try running palfix.py on beedrill's sprite, maybe it'll fix this issue

it might be something specific to ubuntu? I've never seen this issue but I'm building from windows subsystem for linux

if it fixes the issue and the sprites are working fine in-game feel free to make a PR with the sprite modifications

**Comment by Neves97** [comment]
After running on palfix 
```
root@DESKTOP-S0K7P95:/home/pureRGB/gfx/pokemon/front# python3 palfix.py beedrill.png
beedrill.png has too many colors!
```
Beedrill.png contains 7 colors instead of the expected 4, as indicated by Gimp. It appears that some of the PNG files in the project have more than 4 colors. I will edit them and try again.

**Comment by Vortyne** [comment]
yeah, usually rgbds is able to set slightly off extra colors to the correct one to result in 4 - not sure why rgbds would sometimes complain about it for one person but approximate them correctly for others

**Comment by Neves97** [comment]
Done!  2 sprites was causing the trouble.
But strangely, I can build only once, after that the error `make: Nothing to be done for 'all'.` pops up on next attempts.

**Comment by Vortyne** [comment]
that's how make works, it only does something if you've changed something
if you want to rebuild everything from scratch, you need to run `make clean`
then run `make` again
if you want to build a specific version only, you can run
`make blue` or `make red` or `make green` or `make blue_debug`

blue_debug is used for testing, if you press select on the title screen you will get into game very quickly with a full pokedex and high level team

**Comment by Vortyne** [comment]
I made a commit that should fix goldeen/beedrill sprites for people in the future

**Comment by Neves97** [comment]
I didnt know that! Thank you for the explanation and support! Everthing is working as intended!  :)
