### ISSUE TITLE
revive bug

### ISSUE THREAD

**Issue by mattpilott** [Vortyne/pureRGB#48]
hello, when purchasing revive from a mart it does not end up in the bag meaning it is unusable

**Comment by Vortyne** [comment]
which mart?

**Comment by mattpilott** [comment]
i neglected to note that down when i experienced it and now seems to work, tried them all so closing for now

**Comment by Vortyne** [comment]
i've never really messed with the pokemart code (at least on 2.4.5 version) so it's unlikely something is wrong unless it's a bug in the original game

it *could* be something with the bag code since I've messed with that, but I've never messed with how items are added/removed from the bag
