### ISSUE TITLE
Add an option to not enable all 151 Pokémon? (And other ways to differentiate versions)

### ISSUE THREAD

**Issue by pressRtowin** [Vortyne/pureRGB#49]
This might not be a popular opinion, but I actually enjoy that you can't get every Pokémon in just one game. I feel like it adds to the identity of each version and gives you a reason to play each. Any chance of either adding an option to disable this, or making a version of the patches with just that removed and all other additions intact? Perhaps even the option to only unlock Pokemon not originally available in the game after defeating the elite four, if you want to still keep the game 100% beatable on its own.

You could also differentiate the versions further by using each version's respective pokedex entries (using fire red's translation as a base for Red/Green as shin Pokémon does). Just throwing ideas out there, but maybe change up the encounters as Japanese Blue did compared to Red/Green? As long as you're adding bonus areas, maybe a version exclusive area for each could be a cool addition (as black/white have).

But really the main thing is the version exclusives.

**Comment by Vortyne** [comment]
1. Red and Blue have the same pokedex entries (don't care about fire red/leaf green)
2. All pokemon will always be available in all versions of PureRGB
3. Not interested in making the games more confusing by the versions having differing pokemon in different areas.
4. This is for bug reporting, not suggestions
