### ISSUE TITLE
Soft Lock (PureGreen)- Start of game - Table Tile added to Oak's Lab

### ISSUE THREAD

**Issue by Niftystrings** [Vortyne/pureRGB#54]
When starting a patched rom with the latest Pokemon_PureGreen_v2.5.3 patch, there is a table tile that is bugged and changes the floor tiles of Oak's lab making it soft lock if you pick any pokemon other than Charmander
![Screenshot 2023-11-25 141356](https://github.com/Vortyne/pureRGB/assets/93417304/ba8d3e54-e490-4445-868d-6577997935ba)

**Comment by Vortyne** [comment]
You patched the wrong ROM

Use the correct ROM as is listed on the download page.

**Comment by Niftystrings** [comment]
You’re absolutely right. My bad!
