### ISSUE TITLE
intro fight text glitch for fished pokemon

### ISSUE THREAD

**Issue by CVerner1** [Vortyne/pureRGB#57]
I was up on Route 25 rechecking that hidden item glitch and after fighting Lass went to fish.  After fishing every time I fished up a wild pokemon it would say "Lass wants to fight" instead of wild Magikarp/Goldeen appeared.  It's still doing this every time I fish but for the last person I fought, so currently it's saying "Jr. Trainer wants to fight" when I fish up a wild pokemon.  This glitch is not affecting Pokemon encountered on land.

**Comment by Vortyne** [comment]
I am able to reproduce it, will take a look and fix

Probably caused by a bunch of code optimization I did between 2.5.3 and 2.5.4

**Comment by Vortyne** [comment]
Yes, it was just an error in my optimizations, will fix in next release
