### ISSUE TITLE
Sharpen and Bide not animating but still working

### ISSUE THREAD

**Issue by CVerner1** [Vortyne/pureRGB#58]
Occasionally Sharpen and Bide will not animate but the move will still work and the attack/accuracy/defense still increases according to the battle text.  

Also with Bide sometimes the text will say "nothing Happened" and there will be no animation, yet the attack will still increase while the defense doesn't or vice versa with the defense increasing but not the attack.  I assume that's because one side has "topped out".  Still either the defense or attack is still increasing, you'd think the animation/text would reflect that.

**Comment by Vortyne** [comment]
In pokemon red/blue the message for "x won't go higher!" is "nothing happened!"

Looks strange in this context but it's the correct message.

As for the animation, not sure about that one.

**Comment by Vortyne** [comment]
The animation not happening is because the first stat to boost has been maxed. I'll look into fixing it.

**Comment by Vortyne** [comment]
It will be fixed in the next release
