### ISSUE TITLE
NPC that leads you to Pweter Gym overlaps character when leading him to Pewter Gym

### ISSUE THREAD

**Issue by CVerner1** [Vortyne/pureRGB#59]
When walking past the NPC that leads you to Pewter gym it seems you can walk a few blocks farther than in the vanilla game before he stops you and as a result when he leads you back to Pewter gym his sprite and your sprite overlap during the trip to Pewter gym, it looks very awkward.

**Comment by Vortyne** [comment]
It's probably because of something with the overworld code, like the 60fps changes, but I'm not all that interested in messing with this really messy code from the original game for following people

**Comment by Vortyne** [comment]
Not fixed yet :) might try to fix in next bigger release
