### ISSUE TITLE
Options Screen Pg 2 Wonky

### ISSUE THREAD

**Issue by hobbitdev** [Vortyne/pureRGB#60]
Hey! I'm new to all of this, so I very well could have done something wrong.

I cloned pureRGB, and hit make, and it builds the roms with no error.
But when I load up the game and check the menu, page 2 of the menu is visually wonky; the menu selector moves at a diagonal angle, and the words are interrupted.
I'm not sure if this affects gameplay or is purely visual, but a quick google search and look on pret didn't find me anything.
Apologies if this is either well known or if I did something wrong.

Running mGBA on debian.

let me know if i can provide any other info.

![purergb bug report](https://github.com/Vortyne/pureRGB/assets/157327081/119906b4-e728-4592-93ef-e326dfa72df1)
![purergb bug report 2](https://github.com/Vortyne/pureRGB/assets/157327081/2588f4c9-6017-487c-9c93-58360a1528ae)

**Comment by Vortyne** [comment]
Don't think this is an issue with the code itself, also this doesn't appear to be the latest version as there are more options than that in that page.

**Comment by hobbitdev** [comment]
You're right, it is building 2.3.3.
How do I get the most recent version?
I followed install.md and cloned pureRGB, is that not correct?
