### ISSUE TITLE
PureGreen: Corrupt sound when choosing starter Pokémon/viewing some Pokédex entires [Possible gamebreaking bug]

### ISSUE THREAD

**Issue by 03bgood** [Vortyne/pureRGB#63]
The game starts making weird noises (random Pokémon cries) than sometimes crashes to no sound! This happens with both Bulbasaur and Squirtle. Charmader works fine. This happens in PureGreen and I don't know why. This didn't happen with PureRed. What the hell is going on? Just tried PureBlue and it seems to be working fine, as well. Its just PureGreen that is broken and I patched the English patch of Green, which is the base ROM of Blue.

For clarification, this is the one I patched:

https://www.romhacking.net/hacks/876/

Update: I eventually got it to come out of it after hearing all the random noises, but this issue needs patched. It's very similar to the MissingNo. glitch in Yellow where a bunch of random sounds play, then the game crashes. Sometimes you'll bypass it and the glitch will work fine but it's very, very, very unlikely. I can also repeat this glitch by looking at Bulbasaur's entry in the Pokédex. I don't know why this is happening and how no one else is having this issue. Also, the music stops playing. I think Bulbasaur and Squirtle's Pokédex entires are corrupt, for whatever reason.

**Comment by Vortyne** [comment]
Read the very first line of puregreen's romhacking.net page
