### ISSUE TITLE
Add caught pokemon indicator on wild pokemon battles

### ISSUE THREAD

**Issue by kleozzy** [Vortyne/pureRGB#64]
Hello it seems theres no indicator that a pokemon is already caught when fighting wild pokemon,
Can this be added , would be extremely helpful .

**Comment by Vortyne** [comment]
This is not for suggestions, only bug reports

As for your suggestion, see https://old.reddit.com/r/PokemonROMhacks/comments/17ewbha/a_new_release_of_my_pokemon_redgreenblue_romhack/koigr3t/

**Comment by kleozzy** [comment]
Oh my bad , thanks for the info.
