### ISSUE TITLE
Pure Blue throws errors and becomes a 15.4MB file with marcro or Lunar IPS

### ISSUE THREAD

**Issue by Salast1** [Vortyne/pureRGB#66]
I've been enjoying Pure Red, and have verified that Pure Green builds and plays correctly.

However Pure Blue is not working. I just pulled a fresh Pokemon Blue file and re-attempted to patch Pure Blue which still gives an unplayable, 15.4MB file.

Lunar IPS gives:
"The file has been patched, but the data in the IPS file appears to be truncated or misaligned..."

Version attempted: 2.5.5

**Comment by Vortyne** [comment]
You have not patched the correct rom file.

**Comment by Salast1** [comment]
> You have not patched the correct rom file.

[imgur picture](https://imgur.com/a/PTrqvIe)

I am using this Pokemon Blue Version
CRC32:
d6da8a1a
MD5:
50927e843568814f7ed45ec4f944bd8b
SHA-1:
d7037c83e1ae5b39bde3c30787637ba1d4c48ce2

And have successfully built PureGreen with it.

Could you tell me what game I'm supposed to use?

**Comment by Vortyne** [comment]
You have not patched the correct file or have not used the correct patch file

**Comment by epman100** [comment]
I don't know why the OP is encountering patching problems with Pure Blue as I cannot reproduce the problem, even with Lunar IPS as I get a working Pure Blue game **1**Mb size (not 15.4Mb) file.

perhaps OP should use a different & more robust or fool-proof patching tool such as either ROM Patcher JS or Floating IPS (Flips) to apply the Pure Blue IPS file onto a clean Pokemon Blue Version USA ROM.  and perhaps obtain a clean Pokemon Blue Version ROM file from another source.

**Comment by Salast1** [comment]
> I don't know why the OP is encountering patching problems with Pure Blue as I cannot reproduce the problem, even with Lunar IPS as I get a working Pure Blue game **1**Mb size (not 15.4Mb) file after properly applying the correct IPS patch file onto the original Blue ROM file.
> 
> perhaps OP should use a different & more robust patching tool such as either [ROM Patcher JS](https://www.romhacking.net/utilities/1365/) or [Floating IPS (Flips)](https://www.romhacking.net/utilities/1040/) to apply the Pure Blue IPS file onto a clean Pokemon Blue Version USA ROM. and perhaps obtain a clean Pokemon Blue Version ROM file from another source.

I solved it same day that Vortyne replied so didn't want to bother him further.

The IPS file for just Blue downloaded incorrectly from github. I had defaulted to blaming the patcher/roms but as soon as I redownloaded the IPS it functioned with my rom and every patcher.

I've beaten it fully and tell others it's my favorite gen 1 Rom.
