### ISSUE TITLE
Cinnabar Island trade for special colored Snorlax gives normal colored Snorlax

### ISSUE THREAD

**Issue by kero0079** [Vortyne/pureRGB#68]
On Cinnabar Island, in the Pokemon research lab, there's a woman who asks for a Lapras in exchange for her Snorlax, which she says is a special, rare color. After completing the trade, it's just a Snorlax with the default color, same as the ones blocking the roads and in the Pokedex.

**Comment by Vortyne** [comment]
Correct, my code was wrong for the last 2 trades.

Will fix in the next release.

You can use the color changer to change it before the next release happens.
