### ISSUE TITLE
Oak PC Pokedex Rating says to get wrong upgrade

### ISSUE THREAD

**Issue by CVerner1** [Vortyne/pureRGB#70]
When getting the Pokedex rated after catching 50 Pokémon, Prof. Oak says to go get the Exp. All from his aide. The features page says Exp.All is supposed to have been replaced by the Booster Chip and that the minimum pokemon caught is supposed to be 80 not 50. .

**Comment by Vortyne** [comment]
I didn't realize he mentioned the item or the Aide there, I'll fix it in the next release.
