### ISSUE TITLE
Controls are locked after using dig (game restart from last save required)

### ISSUE THREAD

**Issue by BafDyce** [Vortyne/pureRGB#74]
I just used Dig for the first time in my playthrough (using Diglett, to get from Rock Tunnel to Lavender Town). When my character re-appeared in front of the Pkmn Center, I could not move, not open the start menu, not get onto the bike. However, the town music plays normally. Therefore, I dont think that the game freezes completely.
The same also happens when I dig from the cave on route 8 to Lavender Town.

Since I havent used dig in the playthrough before that, I cannot say (yet) if this only affects Lavender Town or if it's a general digging issue.

I am running PureRed (sha1 of the patched file `83edf8090e4232e9f095877956d5c0e2bd10a636`). My base red ROM matches the sha1 hash for pokered.gb from the `roms.sha1` file. I am playing with [mGBA](https://mgba.io/) v0.10.3 (latest) on Linux (for the unlikely scenario that this is an emulator bug)

**Comment by Vortyne** [comment]
Yes it's mostly likely a bug I just found last night will be fixed in next release

**Comment by Vortyne** [comment]
For now stick to using POCKET ABRA instead of dig to escape dungeons

**Comment by BafDyce** [comment]
I see! Thanks for the quick response! :) Fortunately, I rarely use these methods anyways as most of the time I just walk around :D
