### ISSUE TITLE
I cant find a rom that allows me play 

### ISSUE THREAD

**Issue by Ratmilkk99** [Vortyne/pureRGB#75]
I've tried playing the purest red version on my gb/gbc emulator and I haven't found one that let's me use it I'd like to know which one would worl for it 

You can message me back @ Victorvaladez99@yahoo.com 

Thank you

**Comment by Vortyne** [comment]
I can't tell you how to find roms unfortunately, but google probably can. Follow the release page's details to patch an original rom of the game once you have one.

**Comment by Ratmilkk99** [comment]
Sorry I meant emulator but I'll look for the latest update maybe that's what I need 

Yahoo Mail: Search, Organize, Conquer 
 
  On Thu, Aug 15, 2024 at 10:22 PM, ***@***.***> wrote:   


I can't tell you how to find roms unfortunately, but google probably can. Follow the release page's details to patch an original rom of the game once you have one.
