### ISSUE TITLE
Wrong version in game

### ISSUE THREAD

**Issue by cromerc** [Vortyne/pureRGB#79]
I just applied the v2.6.1 patch to my files and put them on my handheld yesterday. But didn't play them until today. When starting the game it states v2.6.0. At first I thought it was my mistake and that I had not patched it correctly. So I went and repatched it then put them on the handhelds again to see it still says v2.6.0.

Not a critical bug, but I ended up patching them and copying them to my handhelds twice because of it.

**Comment by Vortyne** [comment]
Oh. I forgot to update the version text. I will fix it now.

**Comment by Vortyne** [comment]
Fixed.

**Comment by cromerc** [comment]
> Oh. I forgot to update the version text. I will fix it now.

Thanks for the quick reply. Very impressive rom hack by the way. I play it on my anbernic rg nano all the time. :)
