### ISSUE TITLE
[Cheat Request]: Max Poke$ Cheat?

### ISSUE THREAD

**Issue by CaelThunderwing** [Vortyne/pureRGB#80]
### Cheat info

an endless struggle for Poke$ can suck the fun for various romhacks, i can understand not wanting to add one but for those that just want a casual play can a Max Poke$ cheat be added?

**Comment by Vortyne** [comment]
You get an absolute insane amount of money by just fighting every training in this romhack but I'll add the cheat in there.

**Comment by Vortyne** [comment]
Updated the cheat file with that cheat
