### ISSUE TITLE
[Review]: Exactly what I was looking for.

### ISSUE THREAD

**Issue by meldridge** [Vortyne/pureRGB#82]
### Did you finish playing the game before leaving a review?

No

### Review Content

This romhack is exactly what I was looking for. It has all the quality of life improvements I wanted, and also changes just enough of the game to keep it interesting. All of the changes are very well designed and fit in with the feel of Gen 1 perfectly. For many, it makes you wonder why the game wasn't built that way to begin with.

If you're after a purely vanilla romhack with just QoL improvements, this isn't it. But I'd encourage you to try it anyway. I wasn't sold on the type changes at first, but I've left them on and I'm quite enjoying them.

**Comment by Vortyne** [comment]
Thanks for the review! If you finish the game fully, feel free to leave another review.
