### ISSUE TITLE
volcano freeze

### ISSUE THREAD

**Issue by ZachBacon** [Vortyne/pureRGB#84]
As the title mentions, once all the volcano is cleared and you exit the volcano the game freezes once blaine unsuits. 

I did not test the game in an emulator. I written the ROM on a midnight trace gbc cart using the burnmaster and played it on both a gba, gbc, and a fpga device called the fpgbc from funnyplaying. It all freezes on those devices.

Edit: forgot to mention this is the 2.6.2 release

**Comment by Vortyne** [comment]
When exactly does it freeze? Does it play a sound effect after he spins or freeze immediately? Does he start walking out? Does he say anything after removing his suit?

**Comment by Vortyne** [comment]
Whether hardware is real or not most likely doesn't matter

**Comment by ZachBacon** [comment]
impatient much? I had to get it processed due to file size.

https://youtube.com/shorts/R4Hq0ctlf_I?feature=share

**Comment by ZachBacon** [comment]
> I just wanted to clarify that a video would be useful, not that you needed to send it _NOW_. Although I think I found the issue in my code. Text is attempted to be printed when it shouldn't be. This is wrong, and since the input is indeterminate, could cause a crash theoretically.
> 
> Thanks for the video link, although your video is private, on youtube you cannot view private videos unless you add people by google account to allow viewing. So I cannot view it. Maybe unlisted would be better.

I made it unlisted instead of private. It should be viewable now.

**Comment by Vortyne** [comment]
Yes, the video looks like it's caused by what I mentioned. Lets see if the new version with the 1 incorrect line of code removed fixes the freeze for you.

**Comment by ZachBacon** [comment]
I'll get my cart ready to write the rom to it.

**Comment by Vortyne** [comment]
Okay the new release is published: https://github.com/Vortyne/pureRGB/releases/latest try that out

**Comment by ZachBacon** [comment]
> Okay the new release is published: https://github.com/Vortyne/pureRGB/releases/latest try that out

That did it! I'll keep on playing and see if I can uncover more issues on hardware, but I don't think there should be much really to uncover. I think it was just a fluke I found this one.

**Comment by Vortyne** [comment]
I've played through the whole game on real hardware previously. There isn't particularly any difference between that and something such as mgba or bgb (what I test the game on). If you play on VBA like a lot of people do you will have a massively shite experience since it's a bad gameboy emulator.

**Comment by ZachBacon** [comment]
> I've played through the whole game on real hardware previously. There isn't particularly any difference between that and something such as mgba or bgb (what I test the game on). If you play on VBA like a lot of people do you will have a massively shite experience since it's a bad gameboy emulator.

That hurts... Since I'm one of the project leads for vba-m 😂 but yeah we're trying to improve things as best we can, it's one of the reasons I began to get real hardware. Deal with edge cases and try and fix them in vba-m

**Comment by Vortyne** [comment]
Well, you may have fixed this by now, but the biggest issue I had with VBA was the music sounded completely and utterly different than actual hardware with channel 8 being extremely loud. For years this bug plagued youtube streams of game boy music and made me really hate VBA.

**Comment by ZachBacon** [comment]
> Well, you may have fixed this by now, but the biggest issue I had with VBA was the music sounded completely and utterly different than actual hardware with channel 8 being extremely loud. For years this bug plagued youtube streams of game boy music and made me really hate VBA.

To be fair, I understand, for a while vba went stagnant and went under spurts of development. And not every fork had the same interests in mind. We're still dealing with a lot of issues from way back and trying to resolve them as best we can.
