### ISSUE TITLE
Can't catch Magnemite

### ISSUE THREAD

**Issue by sidnoway** [Vortyne/pureRGB#86]
I've been trying to Catch 'em All™ and I noticed that Magnemite's encounter data is in Route 10.

Unfortunately, there is no grass in Route 10. So that's a bit of a dead stop there.

I could see resolving this by putting a small patch of grass in the top left corner above the male trainer.

**Comment by Vortyne** [comment]
Every route has grass. There's grass north of rock tunnel. Which is why Magnemite appears there, since it's in the vicinity of the power plant. Why would I miss something that big?

**Comment by sidnoway** [comment]
Idk chief no need to be hostile but big ups love the game lmao

**Comment by sidnoway** [comment]
my bad bro i forgot about gen 1's crazy ass routes, i really should not have lol
